### ISSUE TITLE
Remove the `-multi` tag from cross-platform images

### ISSUE THREAD

**Issue by agross** [pact-foundation/pact-ruby-cli#116]
Why is there a need to append `-multi` to the tag? If the `latest` tag would be cross-platform:

* as a user you would not need to know about the `-multi` tag
* users would download the same amount of data from the image registry

**Comment by YOU54F** [comment]
We are just being cautious in our roll out as the pact-cli and pact-broker images which follow the same pattern are used my many across production workloads.

Once we've assessed usage levels and any issues raised, we will promote to first class (ie without the appended `-multi` flag.

See here for discussion/agreement on how we would proceed

https://github.com/pact-foundation/pact-broker-docker/pull/123#issuecomment-1534054561

**Comment by YOU54F** [comment]
>users would download the same amount of data from the image registry

no they wouldn't, the images are not the same size, as they are built for different architectures and don't contain the same code...

**Comment by agross** [comment]
> no they wouldn't

docker is smart enough to just pull the parts of the image that match the CPU architecture.

**Comment by YOU54F** [comment]
that isn't the same amount of data as per your statement. 

the amd64 images are tried and tested for many years. the arm64 and arm images are different, and not as rigorously tested.

**Comment by YOU54F** [comment]
size isn't the issue anyway
