### ISSUE TITLE
V1.x Release

### ISSUE THREAD

**Issue by YOU54F** [pact-foundation/pact-ruby-cli#117]
Hey all,

Just to let you know we will be promoting to a V1.x release very shortly, 

It will do the following at the moment

- Promote to 1.x (long overdue 
- Drop the `-latest` suffix from images, and produce multi-arch images against the `latest` tag
  - This will allow arm64/arm users to natively use the `latest` flag without having to force a `linux/amd64` platform. #116 
- Revert to the previous version scheme
  - New changes were introduced and documented [here](https://github.com/pact-foundation/pact-ruby-cli#versioning)
  - The versioning scheme used the M.m.p from the Pact Cli gem, with an additional RELEASE number at the end (eg. 0.51.0.4)
    - pact-cli gem version number https://github.com/pact-foundation/pact-ruby-cli/blob/master/lib/pact/cli/version.rb

**Comment by YOU54F** [comment]
So,



1. first off, I am a numpty. I did a minor release, rather than a major!

2. For reasons I cannot fathom at the moment, the only one now with a multi flag, it the major tag `0`

<img width="953" alt="Screenshot 2023-09-08 at 19 32 05" src="https://github.com/pact-foundation/pact-ruby-cli/assets/19932401/177c2251-672f-4830-bf3d-8161ec0ebaaf">


It doesn't make sense as the script is running the same command , albeit with a different tag, each time

https://github.com/pact-foundation/pact-ruby-cli/blob/master/script/release-workflow/docker-push.sh

**Comment by YOU54F** [comment]
Right, so it doesn't look like the version increment is considered in this release workflow, so regardless of the user input, its defaulting to `minor`

1. on release workflow, we set an increment, this might be set manually when dispatching the workflow, or automatically by the gem update, which invokes the release workflow
  - https://github.com/pact-foundation/pact-ruby-cli/blob/bff4fe64fdaae6f5990c703884cebfd5cba834d5/.github/workflows/release_image.yml#L10-L17
2. we pass it through to `script/release-workflow/run.sh` 
  - https://github.com/pact-foundation/pact-ruby-cli/blob/bff4fe64fdaae6f5990c703884cebfd5cba834d5/.github/workflows/release_image.yml#L54
3. The env vars are setup in this script `. ${script_dir}/set-env-vars.sh`
  - https://github.com/pact-foundation/pact-ruby-cli/blob/bff4fe64fdaae6f5990c703884cebfd5cba834d5/script/release-workflow/run.sh#L12
4. `set-env-vars.sh` calls out to `script/release-workflow/next-docker-tag.sh` to get the docker tag name
  - https://github.com/pact-foundation/pact-ruby-cli/blob/bff4fe64fdaae6f5990c703884cebfd5cba834d5/script/release-workflow/set-env-vars.sh#L19
5. the docker tag is computed and constructed using the version from `lib/pact/cli/version.rb`
  - uses the format `${gem_version}-<dupe_identifier>` 
    - This provides a distinct docker tag, where a new Docker image is released, and the underlying gems haven't been updated (example would be alpine base image update, or ruby version update with no updates to the gems)
  - https://github.com/pact-foundation/pact-ruby-cli/blob/bff4fe64fdaae6f5990c703884cebfd5cba834d5/script/release-workflow/next-docker-tag.sh#L20
  
 How should we compute the Docker tag version?
 
 Should we record all the changes, simply, in the pact cli gem version?
 
 - major/minor/patch update to pact cli gem version depending on the update of a packaged pact-* gem
   - triggers a release of the workflow, with the major/minor/patch  INCREMENT set, as triggered by the underlying pact-* gem update
 - a major/minor/patch update to the docker image, but not the gem, should trigger a pact cli gem version update

**Comment by YOU54F** [comment]
hmm

snags.

1. incorrect referencing of pact broker here
  - https://github.com/pact-foundation/pact-ruby-cli/blob/7ea69c6b61a261adad61cbda6d152322c4507018/script/release-workflow/next-docker-tag.sh#L6
  - this means we wont get the right value here
  - https://github.com/pact-foundation/pact-ruby-cli/blob/7ea69c6b61a261adad61cbda6d152322c4507018/script/release-workflow/next-docker-tag.sh#L14

do we want something like



```
  if [ -n "$INCREMENT" ]; then
    bundle exec bump $INCREMENT --no-commit --replace-in $PWD/lib/pact/cli/version.rb > /dev/null
  fi
  ```
  
  in 
  
  https://github.com/pact-foundation/pact-ruby-cli/blob/7ea69c6b61a261adad61cbda6d152322c4507018/script/release-workflow/next-docker-tag.sh#L8
  
and commit back the updated versions, as part of the docker release, which will catch docker release changes, and also releases triggered by gem updates

**Comment by YOU54F** [comment]
also wat?! These were the same codebases albeit in different forks. - still not publishing multi manifests correctly

<img width="991" alt="Screenshot 2023-09-11 at 20 27 11" src="https://github.com/pact-foundation/pact-ruby-cli/assets/19932401/8c49393c-5c60-4266-931c-b747d5ab427e">

but did on the fork see https://github.com/pact-foundation/pact-ruby-cli/issues/117#issuecomment-1714206821

**Comment by YOU54F** [comment]
Published 0.56.0.5 and oddly, one of the pushes gets associated with @bethesque account, but the other two which are published linux/amd64 only are associated with the pactfoundation account.

![image](https://github.com/pact-foundation/pact-ruby-cli/assets/19932401/1a063abd-dcce-4d40-a2e9-6eb0393a3a61)

This doesn't really make sense, as there is only one set of credentials (DOCKERHUB_USERNAME and DOCKERHUB_TOKEN which are set at the pactfoundation org level, so not sure why Beth's account is being picked up here)


I tested out again on my fork, but forget there was a hard-coded org name, so I published to the pact-foundation account.

This has published the multi-manifests across all builds, with no other code changes. Could it be that we just need to update the org wide docker account and token in gh actions. Such confuse 😬 

![Screenshot 2023-11-13 at 15 37 30](https://github.com/pact-foundation/pact-ruby-cli/assets/19932401/7b6ee5ac-a79c-4f8a-9b9e-175e4558b3e4)

**Comment by bethesque** [comment]
I'm as confused as you are, if not more.

**Comment by YOU54F** [comment]
So I've worked it out now, there was an automated build trigger in docker, which was clobbering the multi-manifest builds, with an amd64 only. Disabled now in Dockerhub and pushed out a patch version to go out.

![image](https://github.com/pact-foundation/pact-ruby-cli/assets/19932401/bd7f7f4c-de75-4e2c-bea1-69a6d0ccc42a)

What a doozy! I thought I was literally going mad. 

![image](https://github.com/pact-foundation/pact-ruby-cli/assets/19932401/0fe312fa-dd94-4ce7-b34c-189e85db75c3)

![image](https://github.com/pact-foundation/pact-ruby-cli/assets/19932401/4c4e8eb1-79be-4a9b-9d7f-978845d22243)
