### ISSUE TITLE
is it possible to get the consumer/provider list and see result for each for latest version of  a tag

### ISSUE THREAD

**Issue by vivekthangathurai** [pact-foundation/pact-ruby-cli#13]
say I have 

consumer 1 and provider 1
consumer 1 and provider 2
I would like to see the latest result for the latest tag..  on consumer 1 and consumer 2

**Comment by bethesque** [comment]
Use [can-i-deploy](https://github.com/pact-foundation/pact_broker-client#can-i-deploy)

**Comment by vivekthangathurai** [comment]
Yes. Thanks
