### ISSUE TITLE
broker publish only tags the first consumer with multible files

### ISSUE THREAD

**Issue by jimmypoms** [pact-foundation/pact-ruby-cli#14]
When using `broker publish` with multiple files and providing a tag, only the first consumer gets tagged correctly.

E.g. when invoking the following command:
```
docker run -v `pwd`:/opt/workspace --rm -e PACT_DISABLE_SSL_VERIFICATION=true -e PACT_BROKER_BASE_URL="<pact-broker-url>" pactfoundation/pact-cli:0.3.0-1 broker publish --tag=master --consumer-app-version=1.0 /opt/workspace/pacts/xxx-zzz.json /opt/workspace/pacts/yyy-zzz.json
```
only the consumer `xxx` gets tagged with master instead of both consumers `xxx` and `yyy`.

Command output:
```
Tagging version 1.0 of xxx as "master"
Publishing xxx/zzz pact to pact broker at <pact-broker-url>
The given version of pact is already published. Overwriting...
The latest version of this pact can be accessed at the following URL (use this to configure the provider verification):
<pact-broker-url>/pacts/provider/zzz/consumer/xxx/latest
Publishing yyy/zzz pact to pact broker at <pact-broker-url>
The given version of pact is already published. Overwriting...
The latest version of this pact can be accessed at the following URL (use this to configure the provider verification):
<pact-broker-url>/pacts/provider/zzz/consumer/yyy/latest
```

**Comment by bethesque** [comment]
You cannot use the same publication task with different consumers.

**Comment by bethesque** [comment]
See https://github.com/pact-foundation/pact_broker-client/issues/29

**Comment by jimmypoms** [comment]
Fair enough :slightly_smiling_face: 

In our case, we do have a monorepo using the same version for different consumers. Currently, we have a Jenkins pipeline step to publish all the pacts for all the consumers where we loop through all the files publishing them individually in order to also be able to tag them, so no blocker of any kind.

I was just wondering whether instead of raising an error in this situation, might it be a simpler change to handle this situation as it seems to be a valid use case with the monorepo. But then, my ruby knowledge is close to non-existant :man_shrugging: just my five cents :wink:

**Comment by bethesque** [comment]
I'll give it some thought, thanks @jimmypoms
