### ISSUE TITLE
Username env var is ignored by webhook commands

### ISSUE THREAD

**Issue by gruntster** [pact-foundation/pact-ruby-cli#20]
Webhook commands fail to successfully authenticate with the Pact Broker when passing credentials via environment variables.

e.g.
> export PACT_BROKER_USERNAME=pbuser
> export PACT_BROKER_PASSWORD=pbpassword
>
> pact-broker create-or-update-webhook http://webhook -X POST -u whuser:whpassword -b https://pactbroker/ --uuid 00000000-0000-0000-0000-000000000000 --provider Provider --contract-content-changed

Error response:
> PactBroker::Client::Hal::ErrorResponseReturned - Error retrieving https://pactbroker/ status=401

However passing the username as a long parameter works, e.g.
> export PACT_BROKER_USERNAME=pbuser
> export PACT_BROKER_PASSWORD=pbpassword
> 
> pact-broker create-or-update-webhook http://webhook -X POST -u whuser:whpassword -b https://pactbroker/ --uuid 00000000-0000-0000-0000-000000000000 --provider Provider --contract-content-changed **--broker-username=${PACT_BROKER_USERNAME}**

Is the `-u` parameter clashing?
https://github.com/pact-foundation/pact_broker-client/blob/master/lib/pact_broker/client/cli/custom_thor.rb#L26
https://github.com/pact-foundation/pact_broker-client/blob/master/lib/pact_broker/client/cli/custom_thor.rb#L101

**Comment by bethesque** [comment]
Yes, the -u was clashing. I've released the fix.
