### ISSUE TITLE
Docker entrypoint isn't consistent with official images

### ISSUE THREAD

**Issue by andreroggeri** [pact-foundation/pact-ruby-cli#38]
I was trying to run the docker image on Jenkins but it failed because the entrypoint only accepts the cli commands.

Jenkins runs something linke `docker run pactfoundation/pact-cli cat` and the entrypoint passes `cat` to the `pact-broker` cli, but it should call the `cat` binary.

The error points to the docker documentation regarding consistency of entrypoints, from what I understood to make it compliant it would change how the image is called (Or map all commands on the entrypoint)

```
ERROR: The container started but didn't run the expected command. Please double check your ENTRYPOINT does execute the command passed as docker run argument, as required by official docker images (see https://github.com/docker-library/official-images#consistency for entrypoint consistency requirements).
Alternatively you can force image entrypoint to be disabled by adding option `--entrypoint=''`.
```

This is a minor inconvenience but I though it was worth to bring it up here. (The workaround overriding the entrypoint worked though)

**Comment by bethesque** [comment]
Would you like to raise a PR with your proposed change so we can discuss the impact?

**Comment by bethesque** [comment]
I had a play around and then realised the build was broken, so I had to fix all the package versions, so I just kept going and I think I've gotten it working the way it's meant to here https://github.com/pact-foundation/pact-ruby-cli/pull/40

Just trying to work out if this is backwards incompatible in any way.

**Comment by bethesque** [comment]
The fix for this is out.
