### ISSUE TITLE
Docker images should be tagged with a specified version

### ISSUE THREAD

**Issue by pawelpaduch** [pact-foundation/pact-ruby-cli#6]
At the moment pact-foundation publishes new version of pact images  which are always  tagged as **latest**.
Here we see that there is only one version of docker image: 
https://hub.docker.com/r/pactfoundation/pact-cli/tags

Every published image should be tagged with specific version e.g. 0.4 , 0.5 . Every new docker image is generated, the version should be bumped. 

Usage of **pact-cli** is not easy due to lack of versioning.  On some build systems it is impossible to update docker image if the image is tagged with the same tag e.g. **latest** .
It means that running  the following command on different machines at the same time will result  that different docker images are used on those machines.   
```
docker pull pactfoundation/pact-cli:latest
```

**Comment by bethesque** [comment]
This is under way, I just have to finish off the last bit of work to do this.

**Comment by bethesque** [comment]
I've done a manual tag of `0.1.0-1` in the meantime.

**Comment by bethesque** [comment]
The versioning is now M.m.p.RELEASE.
