### ISSUE TITLE
alpine3.15 used in 2 docker images but possibly unsupported?

### ISSUE THREAD

**Issue by YOU54F** [pact-foundation/pact-ruby-cli#60]
> alpine:3.15 only has packages for ruby 3.0, and we currenly only support 2.7

from https://github.com/pact-foundation/pact-ruby-cli/commit/a765d0ed5dd971c5b8e2644ed8ff2273ab160474

do we need to downgrade

https://github.com/pact-foundation/pact-ruby-cli/blob/master/Dockerfile-bundle-base
https://github.com/pact-foundation/pact-ruby-cli/blob/master/Dockerfile-node-14

as these both use alpine:3.14 base images

**Comment by bethesque** [comment]
I'm not sure. If the builds pass, then they should be fine.
