### ISSUE TITLE
Docker verify command verifies both latest and passed PACT_URL

### ISSUE THREAD

**Issue by cmoiccool** [pact-foundation/pact-ruby-cli#7]
Hi,

I am implementing pact webhooks on a pact-broker to verify changed pacts. The webhook triggers a docker-compose file like this : 
```
version: '3.5'
services:
  pact_verifier:
    image: pactfoundation/pact-cli:latest
    environment:
      - PACT_BROKER_USERNAME
      - PACT_BROKER_PASSWORD
      - PACT_BROKER_BASE_URL
      - PACT_STATES_SETUP_URL
      - PROVIDER
      - VERSION
      - PACT_URL
    command: >
      verify $PACT_URL
      --provider-base-url $PACT_BROKER_BASE_URL
      --provider-states-setup-url $PACT_STATES_SETUP_URL
      --provider $PROVIDER
      --broker-username $PACT_BROKER_USERNAME
      --broker-password $PACT_BROKER_PASSWORD
      --pact-broker-base-url $PACT_BROKER_BASE_URL
      --publish-verification-results
      --provider-app-version=$VERSION
```
I can see that the verify command runs two verification, one with the pact url for the latest version of the pact and one with the pact url passed as a parameter.
I am wondering if this is the expected behaviour?
If it is, isn't there a chance that in case of a delay between the changed pact webhook and the ci job run, if another change to the pact occurs, when the job finally runs two different version of the pact will be verified on the same ci verification job?

**Comment by bethesque** [comment]
It's because you've specified the provider name as well as the pact URL, so it thinks you want to automatically fetch the pacts for that provider. If you just want to verify the pact, remove the `--provider` parameter.

**Comment by cmoiccool** [comment]
I tried removing the `--provider` parameter but then no pact is verified and i get this message:
`No value provided for required option '--provider'`

The docker-compose without the `--provider` parameter was like this:
```
version: '3.5'
services:
  pact_verifier:
    image: pactfoundation/pact-cli:latest
    environment:
      - PACT_BROKER_USERNAME
      - PACT_BROKER_PASSWORD
      - PACT_BROKER_BASE_URL
      - PACT_STATES_SETUP_URL
      - PROVIDER
      - VERSION
      - PACT_URL
    command: >
      verify $PACT_URL
      --provider-base-url $PACT_BROKER_BASE_URL
      --provider-states-setup-url $PACT_STATES_SETUP_URL
      --broker-username $PACT_BROKER_USERNAME
      --broker-password $PACT_BROKER_PASSWORD
      --pact-broker-base-url $PACT_BROKER_BASE_URL
      --publish-verification-results
      --provider-app-version=$VERSION
```

**Comment by cmoiccool** [comment]
Ok, i managed to make it work the way i was trying.
In order to verify only the pact passed in `$PACT_URL` i needed to remove both the `--provider` parameter and the `--pact-broker-base-url` parameter.
This compose file verified only the pact from the broker webhook :
```
version: '3.5'
services:
  pact_verifier:
    image: pactfoundation/pact-cli:latest
    environment:
      - PACT_BROKER_USERNAME
      - PACT_BROKER_PASSWORD
      - PROVIDER_STATES_SETUP_URL
      - PROVIDER_BASE_URL
      - VERSION
      - PACT_URL
    command: >
      verify $PACT_URL
      --provider-base-url $PROVIDER_BASE_URL
      --provider-states-setup-url $PROVIDER_STATES_SETUP_URL
      --broker-username $PACT_BROKER_USERNAME
      --broker-password $PACT_BROKER_PASSWORD
      --publish-verification-results
      --provider-app-version=$VERSION
```

**Comment by bethesque** [comment]
Oh, that makes sense, yes. Giving it the broker URL is the trigger for it to automatically try and determine the pacts for you, and once you've done that, then the provider name is required. Sorry that didn't occur to me. Glad you've worked it out.
