### ISSUE TITLE
Unable to build Dockerfile.

### ISSUE THREAD

**Issue by cooperaj** [pact-foundation/pact-ruby-cli#72]
I'm attempting to build the Dockerfile locally for aarch64 support but it's failing to build with the error 

```ERROR: unable to select packages:
  build-base-0.5-r3:
    breaks: build-dependencies-20220708.111431[build-base=0.5-r2]
```

I think this is because the r3 release of this package has superceeded r2 in alpine-3.14. Replacing the specification of that package with r3 lets the build continue as normal.

**Comment by bethesque** [comment]
Thanks. I've updated that now.
