### ISSUE TITLE
Mock service link no longer working in Readme

### ISSUE THREAD

**Issue by alexjjseppala** [pact-foundation/pact-ruby-cli#8]
The [link](https://cloud.docker.com/u/pactfoundation/repository/docker/pactfoundation/pact-mock-service) in the [mock service section](https://github.com/pact-foundation/pact-ruby-cli#mock-service) of the readme redirects to 404. 
Should it be replaced with https://hub.docker.com/r/pactfoundation/pact-mock-service despite the pact-mock-service repo being marked as [deprecated](https://github.com/pact-foundation/pact-mock-service-docker)?

**Comment by alexjjseppala** [comment]
The pact-mock-service can be run with `docker run -dit --rm -p 80:80 --name=pact-mock-service -v {host pacts directory}:/app/pacts pactfoundation/pact-cli:latest mock-service -p 80 --host 0.0.0.0 --pact-dir /app/pacts`

**Comment by alexjjseppala** [comment]
Link fixed! https://github.com/pact-foundation/pact-ruby-cli/commit/d4cb1ab1acfe7baa6c00174a8953aa791efed557

**Comment by bethesque** [comment]
I've updated the docs instead https://github.com/pact-foundation/pact-ruby-cli/commit/0d5da5585245281b5fc0b92316a2c22b54b6860a
