### ISSUE TITLE
Release should be bumping minor version, not release version

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-ruby-cli#80]
Last tags are 

0.50.0.31, 0.50.0.30, 0.50.0.29.

Unless they were actually package updates, they should have been 0.48.0, 0.49.0, 0.50.0

**Comment by YOU54F** [comment]
Yeah this is bizarre, when selecting release `minor` and was seeing the 4th digit in the semver changing.

`0.51.0.4`
`0.51.0.3`
`0.51.0.2`

which isn't right, I'll add this on the list of yak shavers, and test out on my fork

**Comment by YOU54F** [comment]
Tagging format should be updated and sorted now.

Releasing the image, will bump the first portion of the `semver` by a minor, and leave the informational part `pactcli-<semver>` the same (as there is no gem bump in this release)

![Screenshot 2023-05-24 at 13 34 55](https://github.com/pact-foundation/pact-ruby-cli/assets/19932401/b5a34fca-c7b7-46ae-b29b-d6596ae7e147)
